### ISSUE TITLE
Option to turn off particle effect in Creative+ UI

### ISSUE THREAD

**Issue by VeraSimon** [exaskye/NotEnoughCreativity#24]
Title pretty much says it all. Could you please add a config option to disable the particle effects when in the Creative+ UI?

**Comment by exaskye** [comment]
As a stopgap, as NEC+ has no config system, I've added a system property under the assumption you want this as you find the particles distracting or otherwise problematic and would prefer a messy solution to no solution at all.

Add `-Dnotenoughcreativity.disableGuiParticles=true` to your JVM arguments with 1.3.0 or later.

**Comment by VeraSimon** [comment]
That'll work for now, but yeah, they get super distracting with the ADHD. Would still like to see a proper config some day, but understand that writing up a whole config system isn't trivial work. Thanks, and will let you know if I run into any issues with this.
